package com.bawei.dianshangjin07.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.dianshangjin07.bean.CommodityData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMMODITY_DATA".
*/
public class CommodityDataDao extends AbstractDao<CommodityData, Long> {

    public static final String TABLENAME = "COMMODITY_DATA";

    /**
     * Properties of entity CommodityData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CommodityId = new Property(0, long.class, "commodityId", true, "_id");
        public final static Property CommodityName = new Property(1, String.class, "commodityName", false, "COMMODITY_NAME");
        public final static Property MasterPic = new Property(2, String.class, "masterPic", false, "MASTER_PIC");
        public final static Property Price = new Property(3, double.class, "price", false, "PRICE");
        public final static Property SaleNum = new Property(4, int.class, "saleNum", false, "SALE_NUM");
    }


    public CommodityDataDao(DaoConfig config) {
        super(config);
    }
    
    public CommodityDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMMODITY_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: commodityId
                "\"COMMODITY_NAME\" TEXT," + // 1: commodityName
                "\"MASTER_PIC\" TEXT," + // 2: masterPic
                "\"PRICE\" REAL NOT NULL ," + // 3: price
                "\"SALE_NUM\" INTEGER NOT NULL );"); // 4: saleNum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMMODITY_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CommodityData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCommodityId());
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String masterPic = entity.getMasterPic();
        if (masterPic != null) {
            stmt.bindString(3, masterPic);
        }
        stmt.bindDouble(4, entity.getPrice());
        stmt.bindLong(5, entity.getSaleNum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CommodityData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCommodityId());
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String masterPic = entity.getMasterPic();
        if (masterPic != null) {
            stmt.bindString(3, masterPic);
        }
        stmt.bindDouble(4, entity.getPrice());
        stmt.bindLong(5, entity.getSaleNum());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public CommodityData readEntity(Cursor cursor, int offset) {
        CommodityData entity = new CommodityData( //
            cursor.getLong(offset + 0), // commodityId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // commodityName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // masterPic
            cursor.getDouble(offset + 3), // price
            cursor.getInt(offset + 4) // saleNum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CommodityData entity, int offset) {
        entity.setCommodityId(cursor.getLong(offset + 0));
        entity.setCommodityName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMasterPic(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPrice(cursor.getDouble(offset + 3));
        entity.setSaleNum(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CommodityData entity, long rowId) {
        entity.setCommodityId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CommodityData entity) {
        if(entity != null) {
            return entity.getCommodityId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CommodityData entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
